create table roles (
    id bigint generated by default as identity primary key,
    name varchar(50) not null,
    constraint uk_roles_name unique (name)
);

create table users (
    id bigint generated by default as identity primary key,
    email varchar(150) not null,
    password_hash varchar(255) not null,
    full_name varchar(120) not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    constraint uk_users_email unique (email)
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    constraint pk_user_roles primary key (user_id, role_id),
    constraint fk_user_roles_user foreign key (user_id) references users (id),
    constraint fk_user_roles_role foreign key (role_id) references roles (id)
);

create table patients (
    id uuid primary key,
    first_name varchar(120) not null,
    last_name varchar(120) not null,
    email varchar(150) not null,
    phone varchar(30),
    birth_date date,
    gender varchar(30),
    notes varchar(1000),
    consent_accepted boolean not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_patients_email unique (email)
);

create table anamnesis_templates (
    id uuid primary key,
    name varchar(120) not null,
    description varchar(1000),
    active boolean not null,
    created_at timestamp with time zone not null
);

create table anamnesis_questions (
    id uuid primary key,
    template_id uuid not null,
    label varchar(500) not null,
    helper_text varchar(1000),
    type varchar(50) not null,
    display_order integer not null,
    required boolean not null,
    scoring_weight double precision,
    constraint fk_anamnesis_questions_template foreign key (template_id) references anamnesis_templates (id)
);

create table anamnesis_question_options (
    question_id uuid not null,
    option_order integer not null,
    option_value varchar(255) not null,
    constraint pk_anamnesis_question_options primary key (question_id, option_order),
    constraint fk_anamnesis_question_options_question foreign key (question_id) references anamnesis_questions (id)
);

create table anamnesis_question_option_scores (
    question_id uuid not null,
    option_value varchar(255) not null,
    score_value double precision not null,
    constraint pk_anamnesis_question_option_scores primary key (question_id, option_value),
    constraint fk_anamnesis_question_option_scores_question foreign key (question_id) references anamnesis_questions (id)
);

create table anamnesis_records (
    id uuid primary key,
    patient_id uuid not null,
    template_id uuid not null,
    template_name_snapshot varchar(120) not null,
    created_at timestamp with time zone not null,
    constraint fk_anamnesis_records_patient foreign key (patient_id) references patients (id),
    constraint fk_anamnesis_records_template foreign key (template_id) references anamnesis_templates (id)
);

create table anamnesis_answers (
    id uuid primary key,
    record_id uuid not null,
    question_id uuid not null,
    question_label_snapshot varchar(500) not null,
    question_type_snapshot varchar(50) not null,
    question_display_order_snapshot integer not null,
    question_scoring_weight_snapshot double precision,
    question_option_scores_snapshot varchar(4000),
    answer_value varchar(4000) not null,
    constraint fk_anamnesis_answers_record foreign key (record_id) references anamnesis_records (id),
    constraint fk_anamnesis_answers_question foreign key (question_id) references anamnesis_questions (id),
    constraint uk_anamnesis_answers_record_question unique (record_id, question_id)
);

create table clinical_evaluations (
    id uuid primary key,
    patient_id uuid not null,
    summary varchar(4000),
    diagnosis_hypothesis varchar(4000),
    evaluated_at timestamp with time zone not null,
    constraint fk_clinical_evaluations_patient foreign key (patient_id) references patients (id)
);

create table score_results (
    id uuid primary key,
    patient_id uuid not null,
    anamnesis_record_id uuid,
    total_score double precision,
    classification varchar(40),
    summary varchar(1000),
    score_type varchar(80),
    score_value double precision,
    interpretation varchar(1000),
    calculated_at timestamp with time zone not null,
    constraint fk_score_results_patient foreign key (patient_id) references patients (id),
    constraint fk_score_results_anamnesis_record foreign key (anamnesis_record_id) references anamnesis_records (id)
);

create table score_result_items (
    score_result_id uuid not null,
    item_order integer not null,
    question_id uuid,
    question_label varchar(500) not null,
    question_type varchar(50) not null,
    answer_value varchar(1000),
    contribution double precision not null,
    rule_applied varchar(1000) not null,
    constraint pk_score_result_items primary key (score_result_id, item_order),
    constraint fk_score_result_items_score_result foreign key (score_result_id) references score_results (id)
);

create table patient_photos (
    id uuid primary key,
    patient_id uuid not null,
    anamnesis_record_id uuid,
    file_name varchar(255) not null,
    original_file_name varchar(255) not null,
    content_type varchar(100) not null,
    file_size bigint not null,
    storage_path varchar(500) not null,
    category varchar(20) not null,
    capture_date date,
    notes varchar(1000),
    created_at timestamp with time zone not null,
    constraint fk_patient_photos_patient foreign key (patient_id) references patients (id),
    constraint fk_patient_photos_anamnesis_record foreign key (anamnesis_record_id) references anamnesis_records (id)
);

create table reports (
    id uuid primary key,
    patient_id uuid not null,
    anamnesis_record_id uuid,
    score_result_id uuid,
    title varchar(255) not null,
    summary varchar(3000),
    generated_at timestamp with time zone not null,
    file_name varchar(255) not null,
    storage_path varchar(500) not null,
    report_type varchar(50) not null,
    created_at timestamp with time zone not null,
    constraint fk_reports_patient foreign key (patient_id) references patients (id),
    constraint fk_reports_anamnesis_record foreign key (anamnesis_record_id) references anamnesis_records (id),
    constraint fk_reports_score_result foreign key (score_result_id) references score_results (id)
);

create table report_selected_photo_ids (
    report_id uuid not null,
    display_order integer not null,
    photo_id uuid not null,
    constraint pk_report_selected_photo_ids primary key (report_id, display_order),
    constraint fk_report_selected_photo_ids_report foreign key (report_id) references reports (id),
    constraint uk_report_selected_photo_ids_report_photo unique (report_id, photo_id)
);

create index ix_anamnesis_questions_template_id on anamnesis_questions (template_id);
create unique index ix_anamnesis_questions_template_order on anamnesis_questions (template_id, display_order);
create index ix_anamnesis_records_patient_created_at on anamnesis_records (patient_id, created_at desc);
create index ix_anamnesis_records_template_id on anamnesis_records (template_id);
create index ix_anamnesis_answers_question_id on anamnesis_answers (question_id);
create index ix_clinical_evaluations_patient_evaluated_at on clinical_evaluations (patient_id, evaluated_at desc);
create index ix_score_results_patient_calculated_at on score_results (patient_id, calculated_at desc);
create index ix_score_results_anamnesis_record_id on score_results (anamnesis_record_id);
create index ix_patient_photos_patient_capture_created on patient_photos (patient_id, capture_date desc, created_at desc);
create index ix_patient_photos_patient_category_capture_created on patient_photos (patient_id, category, capture_date desc, created_at desc);
create index ix_patient_photos_anamnesis_record_id on patient_photos (anamnesis_record_id);
create index ix_reports_patient_generated_created on reports (patient_id, generated_at desc, created_at desc);
create index ix_reports_anamnesis_record_id on reports (anamnesis_record_id);
create index ix_reports_score_result_id on reports (score_result_id);
